// Primitivas del panel «Líneas» (ver DESIGN.md → «Dónde vive»).
export { Avatar } from './avatar'
export { Badge } from './badge'
export { Button, ButtonLink, buttonClass, type ButtonSize, type ButtonVariant } from './button'
export { Card, CARD_SHADOW, Inset, Section, SubHeading } from './card'
export { ChannelChip, channelIcon, channelLabel } from './channel'
export { EmptyState } from './empty-state'
export { CHECKBOX, CONTROL, CONTROL_H, Field, FIELD_LABEL, Input, Select, Switch, Textarea } from './field'
export { Icon, type IconName } from './icon'
export { KpiCell } from './kpi-cell'
export { Notice, type NoticeTone } from './notice'
export { Page, PageHeader } from './page-header'
export { SEGMENT_GROUP, SEGMENT_SCROLL, SegmentLink, segmentItem } from './segmented'
export { StatusChip, type ChipTone } from './status-chip'
